<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

namespace aiprovider_ollama;

use core_ai\aiactions\responses\response_generate_text;

/**
 * Process summarise_text action for Ollama provider.
 *
 * @package    aiprovider_ollama
 * @copyright  2024
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
class process_summarise_text extends \core_ai\process_base
{

    /**
     * Process the summarise_text action.
     *
     * @return response_generate_text The response object
     */
    public function process(): response_generate_text
    {
        global $USER;

        // Get configuration
        $apihost = get_config('aiprovider_ollama', 'apihost');
        $model = get_config('aiprovider_ollama', 'model');

        if (empty($model)) {
            $model = 'llama2'; // Default model
        }

        // Force IPv4 for localhost
        $apihost = str_replace('localhost', '127.0.0.1', $apihost);

        // Get the text to summarize from action data
        $actiondata = $this->actiondata;
        $texttosummarise = $actiondata->get_configuration('prompttext') ?? '';

        if (empty($texttosummarise)) {
            return new response_generate_text(
                success: false,
                errorcode: 400,
                errormessage: 'Empty text provided for summarization',
            );
        }

        // Build the prompt for summarization
        $prompt = "Please provide a concise summary of the following text:\n\n" . $texttosummarise;

        // Build the endpoint
        $endpoint = rtrim($apihost, '/') . '/api/generate';

        $data = [
            'model' => $model,
            'prompt' => $prompt,
            'stream' => false
        ];

        // Make the API call
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, $endpoint);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_POST, true);
        curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($data));
        curl_setopt($ch, CURLOPT_HTTPHEADER, ['Content-Type: application/json']);
        curl_setopt($ch, CURLOPT_TIMEOUT, 180);
        curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 15);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);

        $response = curl_exec($ch);
        $error = curl_error($ch);
        $httpcode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
        curl_close($ch);

        if (!empty($error)) {
            return new response_generate_text(
                success: false,
                errorcode: 500,
                errormessage: 'Ollama API error: ' . $error,
            );
        }

        if ($httpcode !== 200) {
            return new response_generate_text(
                success: false,
                errorcode: $httpcode,
                errormessage: 'Ollama API returned HTTP ' . $httpcode,
            );
        }

        $result = json_decode($response, true);
        if (json_last_error() !== JSON_ERROR_NONE) {
            return new response_generate_text(
                success: false,
                errorcode: 500,
                errormessage: 'Invalid JSON response from Ollama API',
            );
        }

        $summary = $result['response'] ?? '';

        if (empty($summary)) {
            return new response_generate_text(
                success: false,
                errorcode: 500,
                errormessage: 'No summary generated by Ollama model',
            );
        }

        // Return successful response
        return new response_generate_text(
            success: true,
            generatedcontent: $summary,
        );
    }
}
